import { FaDiscord } from "react-icons/fa";
import { useRouter } from "next/router";
import { client } from "../lib/graphql/client";
import { UserQuery } from "../lib/graphql/query";
import type { NextPage } from "next";
import Head from "next/head";

const Login: NextPage = () => {
  const router = useRouter();

  const nav = (route: string) => {
    return router.push(route);
  };

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex items-center justify-center w-screen min-h-screen flex-col gap-5">
        <img
          className="block h-40 w-auto rounded-full"
          src="https://cdn.discordapp.com/avatars/772690931539247104/5f0aa26a8e2b83c3d218989b3063615e.png"
          alt="enma"
        />
        <div
          onClick={async () => {
            const { data } = await client.query({
              query: UserQuery,
            });

            return data
              ? nav("/dashboard")
              : nav("http://localhost:8080/api/auth/login");
          }}
          className="text-xl px-10 py-3 ring-1 ring-offset-black hover:bg-slate-800 cursor-pointer flex flex-row gap-3 rounded-md lg:hover:scale-105 duration-200 ease-linear hover:ring-red-400"
        >
          <span>Login with Discord</span>
          <span className="mt-1">
            <FaDiscord color="#7289DA" />
          </span>
        </div>
      </div>
    </>
  );
};

export default Login;
